version: '3'
services:
  client:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4173:3000"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://chch:azerty@cluster0.df9pco0.mongodb.net/
      - JWT_SECRET=vg1x#2L?K39TTXpQ3#
      - JWT_EXPIRES_IN=1h
      - NODE_MAILER_USER=koussayfridhiaziz@gmail.com
      - NODE_MAILER_PASS=ltmnfpfowpzbuetl
      - FRONT_URL=http://localhost:3000/
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    restart: unless-stopped
