services:
  client:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped  # Ensures the container restarts on server reboot

  server:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - NODE_MAILER_USER=${NODE_MAILER_USER}
      - NODE_MAILER_PASS=${NODE_MAILER_PASS}
      - FRONT_URL=${FRONT_URL}
    restart: unless-stopped  # Ensures the container restarts on server reboot
