const data = [
  {
    authors: {
      fr: ["BEN KHEDHER, H.", "YILDIRIM, E.", "BRAHAM, M."],
      en: ["BEN KHEDHER, H.", "YILDIRIM, E.", "BRAHAM, M."],
      ar: ["بن خضر, ه.", "يلدريم, إ.", "براهم، م."],
    },
    title: {
      en: "A checklist of Philanthini and Pseudoscoliini (Hymenoptera: Crabronidae) with new records from Tunisia",
      fr: "Une liste de contrôle des Philanthini et des Pseudoscoliini (Hymenoptera : Crabronidae) avec de nouvelles mentions pour la Tunisie",
      ar: "قائمة تدقيق للفيلانثيني وبسودوسكوليني (Hymenoptera: Crabronidae) مع سجلات جديدة من تونس",
    },
    journal: {
      name: {
        en: "Transactions of the American Entomological Society",
        fr: "Transactions de la Société Entomologique Américaine",
        ar: "معاملات الجمعية الحشرية الأمريكية",
      },
      volume: 147,
      issue: 1,
      pages: "1-10",
      ISSN: {
        electronic: "2162-3139",
        print: "0002-8320",
      },
      url: "https://doi.org/10.3157/061.147.0101",
    },
    published_date: { en: "15 May 2021", fr: "15 mai 2021", ar: "2021-05-15" },
    pdf_url:
      "https://bioone.org/journals/transactions-of-the-american-entomological-society/scope-and-details",
  },
  {
    authors: {
      fr: [
        "DORRA MANSOUR",
        "MERITXELL PÉREZ-HEDO",
        "JOSE CATALÁN",
        "MOHAMED BRAHAM",
        "JOSEP A.JAQUES",
        "ALBERTO URBANEJA",
      ],
      en: [
        "DORRA MANSOUR",
        "MERITXELL PÉREZ-HEDO",
        "JOSE CATALÁN",
        "MOHAMED BRAHAM",
        "JOSEP A.JAQUES",
        "ALBERTO URBANEJA",
      ],
      ar: [
        "دورا منصور",
        "ميرتشيل بيريز-هيدو",
        "جوسيه كاتالان",
        "محمد براهم",
        "جوسيب أ.خاكويس",
        "ألبرتو أوربانيخا",
      ],
    },
    title: {
      en: "Biological control of the citrus leafminer 25 years after its introduction in the Valencia citrus growing area (Spain): A new player in the game",
      fr: "Contrôle biologique du mineur des feuilles des agrumes 25 ans après son introduction dans la région de culture des agrumes de Valence (Espagne) : Un nouvel acteur dans le jeu",
      ar: "التحكم البيولوجي في ديدان أوراق الحمضيات بعد 25 عامًا من إدخالها في منطقة زراعة الحمضيات بفالنسيا (إسبانيا): لاعب جديد في اللعبة",
    },
    journal: {
      name: {
        en: "Biological Control",
        fr: "Contrôle biologique",
        ar: "مكافحة حيوية",
      },
      volume: 155,
      pages: "104529",
      ISSN: "1049-9644",
      url: "https://doi.org/10.1016/j.biocontrol.2020.104529",
    },
    published_date: {
      en: "4 January 2021",
      fr: "4 janvier 2021",
      ar: "2021-01-04",
    },
    pdf_url: "https://www.sciencedirect.com/journal/biological-control",
  },
  {
    authors: {
      fr: [
        "CHIKH-ROUHOU H.",
        "GÓMEZ-GUILLAMÓN ML.",
        "GONZÁLEZ V.",
        "STA-BABA R.",
        "GARCÉS-CLAVER A.",
      ],
      en: [
        "CHIKH-ROUHOU H.",
        "GÓMEZ-GUILLAMÓN ML.",
        "GONZÁLEZ V.",
        "STA-BABA R.",
        "GARCÉS-CLAVER A.",
      ],
      ar: [
        "شيخ روحو ح.",
        "غوميز غيامون مل.",
        "غونزاليز في.",
        "ستا بابا ر.",
        "غارسيس كلافر أ.",
      ],
    },
    title: {
      en: "Cucumis melo L. germplasm in Tunisia: Unexploited sources of resistance to Fusarium wilt",
      fr: "Le germoplasme de Cucumis melo L. en Tunisie : Sources inexploitées de résistance à la fusariose",
      ar: "جراثيم Cucumis melo L. في تونس: مصادر غير مستغلة للمقاومة ضد التذبول الفطري",
    },
    journal: {
      name: {
        en: "Horticulturae",
        fr: "Horticulturae",
        ar: "البستنة",
      },
      volume: 7,
      issue: 8,
      pages: "208",
      ISSN: {
        electronic: "2311-7524",
      },
      url: "https://doi.org/10.3390/horticulturae7080208",
    },
    published_date: {
      en: "22 July 2021",
      fr: "22 juillet 2021",
      ar: "2021-07-22",
    },
    pdf_url: "https://www.mdpi.com/journal/horticulturae",
  },
  {
    authors: {
      fr: [
        "CHIKH-ROUHOU H.",
        "MEZGHANI Najla",
        "MNASRI S.",
        "MEZGHANI N.",
        "GARCÉS-CLAVER A.",
      ],
      en: [
        "CHIKH-ROUHOU H.",
        "MEZGHANI Najla",
        "MNASRI S.",
        "MEZGHANI N.",
        "GARCÉS-CLAVER A.",
      ],
      ar: [
        "شيخ روحو ح.",
        "مزغاني نجلاء",
        "منصري س.",
        "مزغاني ن.",
        "غارسيس كلافر أ.",
      ],
    },
    title: {
      en: "Assessing the genetic diversity and population structure of a Tunisian melon (Cucumis melo L.) collection using phenotypic traits and SSR molecular markers",
      fr: "Évaluation de la diversité génétique et de la structure de la population d'une collection tunisienne de melons (Cucumis melo L.) en utilisant des caractères phénotypiques et des marqueurs moléculaires SSR",
      ar: "تقييم التنوع الوراثي وهيكل السكان لمجموعة من البطيخ التونسي (Cucumis melo L.) باستخدام الصفات الظاهرية والعلامات الجزيئية SSR",
    },
    journal: {
      name: {
        en: "Agronomy",
        fr: "Agronomie",
        ar: "علم الزراعة",
      },
      volume: 11,
      issue: 6,
      pages: "1121",
      ISSN: {
        electronic: "2073-4395",
      },
      url: "https://doi.org/10.3390/agronomy11061121",
    },
    published_date: { en: "31 May 2021", fr: "31 mai 2021", ar: "2021-05-31" },
    pdf_url: "https://www.mdpi.com/journal/agronomy",
  },
  {
    authors: {
      fr: [
        "MAJDOUB S.",
        "CHAABANE-BANAOUES R.",
        "MOKNI R. E.",
        "CHAIEB I.",
        "PIRAS A.",
        "FALCONIERI D",
        "HAMMAMI S.",
      ],
      en: [
        "MAJDOUB S.",
        "CHAABANE-BANAOUES R.",
        "MOKNI R. E.",
        "CHAIEB I.",
        "PIRAS A.",
        "FALCONIERI D",
        "HAMMAMI S.",
      ],
      ar: [
        "مجذوب س.",
        "شعبان بن عويس ر.",
        "مكني ر. ع.",
        "شايب إ.",
        "بيراس أ.",
        "فالكونيري د",
        "حمامي س.",
      ],
    },
    title: {
      en: "Seasonal Variation in the Chemical Profile, Antifungal and Insecticidal Activities of Essential Oils from Daucus reboudii",
      fr: "Variation saisonnière du profil chimique, des activités antifongiques et insecticides des huiles essentielles de Daucus reboudii",
      ar: "التباين الفصلي في الملف الكيميائي، والأنشطة المضادة للفطريات والحشرات للزيوت الأساسية من الجزر المعدلة",
    },
    journal: {
      name: {
        en: "Waste and Biomass Valorization",
        fr: "Valorisation des déchets et de la biomasse",
        ar: "تقدير النفايات والكتلة الحيوية",
      },
      pages: "1-13",
      url: "https://doi.org/10.1007/s12649-021-01594-9",
    },
    published_date: {
      en: "05 November 2021",
      fr: "05 novembre 2021",
      ar: "2021-11-05",
    },
    pdf_url: "https://www.springer.com/journal/12649",
  },
  {
    authors: {
      fr: [
        "HAMOUDA, A. B.",
        "BNINA, E.B.",
        "CHAIEB, I.",
        "LAARIF, A.",
        "JANNET, H. B.",
      ],
      en: [
        "HAMOUDA, A. B.",
        "BNINA, E.B.",
        "CHAIEB, I.",
        "LAARIF, A.",
        "JANNET, H. B.",
      ],
      ar: [
        "حمودة، ع. ب.",
        "بنينة، ع. ب.",
        "شايب، إ.",
        "العريف، ع.",
        "جنات، ح. ب.",
      ],
    },
    title: {
      en: "Cyclic and acyclic alcohols: a structure-activity relationship study correlation between insecticidal activity and chemical structure",
      fr: "Alcools cycliques et acycliques : étude de corrélation entre l'activité insecticide et la structure chimique",
      ar: "الكحولات الدورية وغير الدورية: دراسة علاقة البنية الفعالة بين النشاط المبيد للحشرات والبنية الكيميائية",
    },
    journal: {
      name: {
        en: "International Journal of Tropical Insect Science",
        fr: "Revue internationale de science tropicale des insectes",
        ar: "المجلة الدولية لعلم الحشرات الاستوائية",
      },
      volume: 41,
      issue: 2,
      pages: "961-968",
      ISSN: {
        electronic: "1742-7592",
      },
      url: "https://doi.org/10.1007/s42690-020-00277-7",
    },
    published_date: {
      en: "28 September 2021",
      fr: "28 septembre 2021",
      ar: "2021-09-28",
    },
    pdf_url: "https://www.springer.com/journal/42690",
  },
  {
    authors: {
      fr: [
        "KHALED-GASMI, W.",
        "HAMOUDA, A. B.",
        "CHAIEB, I.",
        "SOUISSI, R.",
        "ASCRIZZI, R.",
        "FLAMINI, G.",
        "BOUKHRIS-BOUHACHEM, S.",
      ],
      en: [
        "KHALED-GASMI, W.",
        "HAMOUDA, A. B.",
        "CHAIEB, I.",
        "SOUISSI, R.",
        "ASCRIZZI, R.",
        "FLAMINI, G.",
        "BOUKHRIS-BOUHACHEM, S.",
      ],
      ar: [
        "خالد قاسمي، و.",
        "حمودة، ع. ب.",
        "شايب، إ.",
        "سويسي، ر.",
        "أسكريزي، ر.",
        "فلاميني، ج.",
        "بوخريس-بوحاشم، س.",
      ],
    },
    title: {
      en: "Natural repellents based on three botanical species essential oils as an eco-friendly approach against aphids",
      fr: "Répulsifs naturels à base de trois huiles essentielles de plantes en tant qu'approche écologique contre les pucerons",
      ar: "مواد دفع طبيعية تعتمد على ثلاثة زيوت أساسية نباتية كنهج صديق للبيئة ضد الخنافس",
    },
    journal: {
      name: {
        en: "South African Journal of Botany",
        fr: "Journal sud-africain de botanique",
        ar: "المجلة الجنوب أفريقية لعلم النبات",
      },
      volume: 141,
      pages: "133-141",
      ISSN: "0254-6299",
      url: "https://doi.org/10.1016/j.sajb.2021.05.001",
    },
    published_date: { en: "24 May 2021", fr: "24 mai 2021", ar: "2021-05-24" },
    pdf_url: "https://journals.elsevier.com/south-african-journal-of-botany",
  },
  {
    authors: {
      fr: [
        "DEBBABI, H.",
        "EL MOKNI, R.",
        "NARDONI, S.",
        "CHAIEB, I.",
        "MAGGI, F.",
        "NZEKOUE, F. K",
        "HAMMAMI, S.",
      ],
      en: [
        "DEBBABI, H.",
        "EL MOKNI, R.",
        "NARDONI, S.",
        "CHAIEB, I.",
        "MAGGI, F.",
        "NZEKOUE, F. K",
        "HAMMAMI, S.",
      ],
      ar: [
        "دبابي، ح.",
        "المكني، ر.",
        "ناردوني، س.",
        "شايب، إ.",
        "ماجي، ف.",
        "نزيكو، ف. ك.",
        "حمامي، س.",
      ],
    },
    title: {
      en: "Chemical diversity and biological activities of essential oils from native populations of Clinopodiummenthifolium subsp. ascendens (Jord.) Govaerts",
      fr: "Diversité chimique et activités biologiques des huiles essentielles des populations autochtones de Clinopodiummenthifolium subsp. ascendens (Jord.) Govaerts",
      ar: "تنوع الكيميائيات والأنشطة البيولوجية للزيوت الأساسية من السكان الأصليين لنوع Clinopodiummenthifolium subsp. ascendens (Jord.) Govaerts",
    },
    journal: {
      name: {
        en: "Environmental Science and Pollution Research",
        fr: "Recherche sur la science de l'environnement et la pollution",
        ar: "بحوث علم البيئة وتلوثها",
      },
      volume: 28,
      issue: 11,
      pages: "13624-13633",
      ISSN: {
        electronic: "1614-7499",
      },
      url: "https://doi.org/10.1007/s11356-020-11523-3",
    },
    published_date: {
      en: "14 November 2020",
      fr: "14 novembre 2020",
      ar: "2020-11-14",
    },
    pdf_url: "https://www.springer.com/journal/11356",
  },
  {
    authors: {
      fr: [
        "MOUMNI M.",
        "ROMANAZZI G.",
        "NAJAR B.",
        "PISTELLI L.",
        "BEN AMARA H.",
        "MEZRIOUI K.",
        "KAROUS O.",
        "CHAIEB I",
        "ALLAGUI M.B.",
      ],
      en: [
        "MOUMNI M.",
        "ROMANAZZI G.",
        "NAJAR B.",
        "PISTELLI L.",
        "BEN AMARA H.",
        "MEZRIOUI K.",
        "KAROUS O.",
        "CHAIEB I",
        "ALLAGUI M.B.",
      ],
      ar: [
        "مومني م.",
        "رومانازي ج.",
        "النجار ب.",
        "بيستيلي ل.",
        "بن عمارة ه.",
        "مزريوي ك.",
        "كاروس أ.",
        "شايب إ.",
        "العلاقي م. ب.",
      ],
    },
    title: {
      en: "Chemical Composition and Insecticidal Activity of Essential Oils from Two Wild Populations of Lavandula stoechas (Lamiaceae) Growing in Tunisia",
      fr: "Composition chimique et activité insecticide des huiles essentielles de deux populations sauvages de Lavandula stoechas (Lamiaceae) en Tunisie",
      ar: "التركيب الكيميائي والنشاط المبيد للزيوت الأساسية من سكان برية لأريكة الجليد (Lamiaceae) المنموة في تونس",
    },
    journal: {
      name: {
        en: "Chemistry & Biodiversity",
        fr: "Chimie et biodiversité",
        ar: "الكيمياء والتنوع البيولوجي",
      },
      volume: 18,
      issue: 6,
      pages: "e2100251",
      ISSN: {
        electronic: "1612-1880",
        print: "1612-1872",
      },
      url: "https://doi.org/10.1002/cbdv.202100251",
    },
    published_date: { en: "24 May 2021", fr: "24 mai 2021", ar: "2021-05-24" },
    pdf_url: "https://onlinelibrary.wiley.com/journal/16121880",
  },
  {
    authors: {
      fr: [
        "AYDI-BEN-ABDALLAH R ",
        "CHIKH-ROUHOU H",
        "JABNOUN-KHIAREDDINE H",
        "STA-BABA R. & DAAMI-REMADI M",
      ],
      en: [
        "AYDI-BEN-ABDALLAH R ",
        "CHIKH-ROUHOU H",
        "JABNOUN-KHIAREDDINE H",
        "STA-BABA R. & DAAMI-REMADI M",
      ],
      ar: [
        "عايدي بن عبد الله",
        "شيخ روحو ح",
        "جبنون خير الدين",
        "ستا بابا ر & دامي ريمادي م",
      ],
    },
    title: {
      en: "Fungal and bacterial rhizosphere microbiome associated with selected melon and snake melon genotypes",
      fr: "Microbiome fongique et bactérien de la rhizosphère associé à des génotypes sélectionnés de melon et de melon serpent",
      ar: "ميكروبيوم الجذور الفطرية والبكتيرية المرتبطة بأنماط وراثية مختارة من البطيخ والبطيخ الثعبان  ",
    },
    journal: {
      name: {
        en: "Journal of Microbiology, Biotechnology and Food Sciences",
        fr: "Journal de microbiologie, biotechnologie et sciences alimentaires",
        ar: "مجلة علم الأحياء الدقيقة والتكنولوجيا الحيوية وعلوم الأغذية",
      },
      volume: 11,
      issue: 3,
      pages: " ",
      ISSN: {
        electronic: "1338-5178. WOS + Scopus.",
        print: " ",
      },
      url: "https://doi.org/10.15414/jmbfs.4004",
    },
    published_date: { en: "05-02-2021", fr: "02-05-2021", ar: "2021-05-02" },
    pdf_url: "https://www.jmbfs.org/",
  },
  {
    authors: {
      en: ["CHIKH-ROUHOU H", "TLILI I", "ILAHY R", "R’HIM T", "STA-BABA R"],
    },
    title: {
      en: "Fruit quality assessment and characterization of melon genotypes",
    },
    journal: {
      name: { en: "International Journal of Vegetable Science" },
      volume: 27,
      issue: 1,
      pages: "3-19",
      ISSN: {
        electronic: "1931-5279",
        print: "1931-5260",
      },
      url: "https://doi.org/10.1080/19315260.2019.1692268",
    },
    published_date: { en: "01 January 2021" },
    pdf_url: "https://www.tandfonline.com/loi/wijv20",
  },
  {
    authors: {
      en: [
        "AYDI BEN ABDALLAH R",
        "AMMAR N",
        "AYED F",
        "JABNOUN-KHIAREDDINE H",
        "DAAMI-REMADI M",
      ],
    },
    title: {
      en: "Single and combined effects of Bacillus spp. and brown seaweed (Sargassum vulgare) extracts as bio-stimulants of eggplant (Solanum melongena L.) growth",
    },
    journal: {
      name: { en: "Advances in Horticultural Science" },
      volume: 35,
      issue: 2,
      pages: "151-164",
      ISSN: {
        electronic: "",
        print: "",
      },
      url: "https://oaj.fupress.net/index.php/ahs/about",
    },
    published_date: { en: "17 July 2021" },
    pdf_url: "",
  },
  {
    authors: {
      fr: ["JERBI M.", "BEN HAMOUDA A.", "HAMDI F.", "LAARIF A.", "CHAIEB I."],
      en: ["JERBI M.", "BEN HAMOUDA A.", "HAMDI F.", "LAARIF A.", "CHAIEB I."],
      ar: ["جربي م.", "بن حمودة أ.", "حمدي ف.", "لعريف أ.", "شعيب إ."],
    },
    title: {
      en: "Fumigant activities of essential oils and their mixtures from cultivated aromatic plants against Spodoptera littoralis (Boisduval, 1833)",
      fr: "Activités fumigantes des huiles essentielles et de leurs mélanges provenant de plantes aromatiques cultivées contre Spodoptera littoralis (Boisduval, 1833)",
      ar: "أنشطة مبيدة للحشرات للزيوت الأساسية ومزاياها من النباتات العطرية المزروعة ضد سبودوبتيرا ليتوراليس (بويسدوفال، 1833)",
    },
    journal: {
      name: {
        en: "Journal of Entomology and Zoology Studies",
        fr: "Journal of Entomology and Zoology Studies",
        ar: "مجلة الدراسات في علم الحشرات والحيوانات البرية",
      },
      volume: 9,
      issue: 2,
      pages: "50-55",
      ISSN: { electronic: "2320-7078. WOS + Scopus.", print: "" },
      url: "https://www.entomoljournal.com/",
    },
    published_date: {
      en: "Mar-Apr 2021",
      fr: "Mar-Apr 2021",
      ar: "مارس-أبريل 2021",
    },
    pdf_url:
      "https://www.entomoljournal.com/archives/2021/vol9issue2/PartA/8-5-374-132.pdf",
  },
  {
    authors: {
      fr: [
        "EL AYEB N.",
        "SMIRI O.",
        "ELAYEB R.",
        "CHAIEB, I.",
        "BEN ATIA I.",
        "SOUGUIR S.",
        "ACHOUR, S.",
      ],
      en: [
        "EL AYEB N.",
        "SMIRI O.",
        "ELAYEB R.",
        "CHAIEB, I.",
        "BEN ATIA I.",
        "SOUGUIR S.",
        "ACHOUR, S.",
      ],
      ar: [
        "العيّاب ن.",
        "سميري أ.",
        "العيّاب ر.",
        "شعيب، إ.",
        "بن عطية إ.",
        "سوقير س.",
        "عاشور، س.",
      ],
    },
    title: {
      en: "Phytochemical study and evaluation of the biological activities of essential oils from aromatic plants (Citrus Limon, Salvia officinalis and Cymbopogon citratus): formulation of food detergent-disinfectant",
      fr: "Étude phytochimique et évaluation des activités biologiques des huiles essentielles de plantes aromatiques (Citrus Limon, Salvia officinalis et Cymbopogon citratus) : formulation de détergent-désinfectant alimentaire",
      ar: "دراسة فيتوكيميائية وتقييم للأنشطة البيولوجية للزيوت الأساسية من النباتات العطرية (Citrus Limon، Salvia officinalis و Cymbopogon citratus): صياغة مطهرات المنظفات الغذائية",
    },
    journal: {
      name: {
        en: "International Journal of Scientific & Engineering Research",
        fr: "International Journal of Scientific & Engineering Research",
        ar: "المجلة الدولية للبحوث العلمية والهندسية",
      },
      volume: 12,
      issue: 4,
      pages: "",
      ISSN: { electronic: "2229-5518", print: "" },
      url: "https://www.ijser.org/onlineResearchPaperViewer.aspx?Phytochemical-study-and-evaluation-of-the-biological-activities-of-essential-oils-from-aromatic-plants-Citrus-Limon-Salvia-officinalis-and-Cymbopogon-citratus-formulation-of-food-detergent-disinfectant.pdf",
    },
    published_date: {
      en: "24 April 2021",
      fr: "24 April 2021",
      ar: "24 أبريل 2021",
    },
    pdf_url: "https://www.ijser.org/",
  },
];

export { data };
